{% set version = "2.14.2" %}

package:
  # https://github.com/conda/conda-build/issues/3933
  name: pytensor-suite
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pytensor/pytensor-{{ version }}.tar.gz
  sha256: dbafae9ce4264e0e5d1e02b2214da3187ca51e99f43a1a2245e5c0d839cf3dfa
  patches:

build:
  number: 0
  skip: true  # [py<39]

outputs:
  - name: pytensor-base
    build:
      script:
        - python -m pip install . --no-deps -vv
      entry_points:
        - pytensor-cache = bin.pytensor_cache:main
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - python                                 # [build_platform != target_platform]
        - setuptools >=48.0.0                    # [build_platform != target_platform]
        - cython                                 # [build_platform != target_platform]
        # Allow numpy pinnings to be managed by conda-forge global dependencies
        - numpy                                  # [build_platform != target_platform]
        - versioneer ==0.28                      # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - tomli                                  # [build_platform != target_platform]
      host:
        - python
        - setuptools >=48.0.0
        - cython
        # Allow numpy pinnings to be managed by conda-forge global dependencies
        - numpy
        - versioneer ==0.28
        - pip
        - tomli
      run:
        - python
        - setuptools >=48.0.0
        - scipy >=0.14
        - filelock
        - etuples
        - logical-unification
        - minikanren
        - cons
        - typing_extensions
        - {{ pin_compatible("numpy") }}
    test:
      imports:
        - pytensor
      commands:
        - pytensor-cache help
        - pip check
        - python check-for-warnings.py allowed-warnings-base.txt
      requires:
        - pip
      files:
        - check-for-warnings.py
        - allowed-warnings-base.txt

  - name: pytensor
    build:
      script:
        - echo "Nothing to build here, just add dependencies."
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('pytensor-base', exact=True) }}
        - {{ compiler('c') }}  # [not win]
        - {{ compiler('cxx') }}  # [not win]
        - gxx  # [linux]
        - {{ compiler('m2w64_c') }}  # [win]
        - {{ compiler('m2w64_cxx') }}  # [win]

        - m2w64-toolchain  # [win]
        # The libpython conda-forge package seems to be a wrapper package
        # which configures m2w64-toolchain for Python.
        # <https://github.com/conda-forge/libpython-feedstock/blob/main/recipe/bld.bat>
        - libpython >=2.2  # [win]

        # mkl-service is only available for linux-64, win-64, and osx-64.
        # For everything else, use openblas.
        - mkl-service  # [linux64 or win64 or (osx and not arm64)]
        - blas  # [not (linux64 or win64 or (osx and not arm64))]
    test:
      imports:
        - pytensor
        - pytensor.configdefaults
      commands:
        - pytensor-cache help
        - pip check
        - python check-for-warnings.py allowed-warnings-main.txt
      requires:
        - pip
      files:
        - check-for-warnings.py
        - allowed-warnings-main.txt

about:
  home: https://github.com/pymc-devs/pytensor
  license: BSD-3-Clause
  summary: An optimizing compiler for evaluating mathematical expressions.
  license_file: LICENSE.txt
  dev_url: https://github.com/pymc-devs/pytensor/
  doc_url: https://pytensor.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - aseyboldt
    - maresb
    - michaelosthege
    - twiecki
