{% set version = "2.25.0" %}

package:
  # https://github.com/conda/conda-build/issues/3933
  name: pytensor-suite
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pytensor/pytensor-{{ version }}.tar.gz
  sha256: 365f8128dd953e3ba5449c3d45b295d32401fa76738f28632f7de2f3df3bc817
  patches:

build:
  number: 0

outputs:
  - name: pytensor-base
    build:
      # NOTE: Keep this line synchronized with the identical one below.
      skip: true  # [py<310]
      script:
        - python -m pip install . --no-deps -vv
      entry_points:
        - pytensor-cache = pytensor.bin.pytensor_cache:main
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - {{ compiler('cxx') }}
        - python                                 # [build_platform != target_platform]
        - setuptools >=59.0.0                    # [build_platform != target_platform]
        - cython                                 # [build_platform != target_platform]
        # Allow numpy pinnings to be managed by conda-forge global dependencies
        # See also <https://matrix.to/#/!SOyumkgPRWoXfQYIFH:matrix.org/$17156774815028VNLdj:matrix.org?via=matrix.org&via=gitter.im&via=salt-rock-lamp.ems.host>
        - numpy                                  # [build_platform != target_platform]
        - numpy <2.0a0                           # [build_platform != target_platform]
        - versioneer ==0.28                      # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - tomli                                  # [build_platform != target_platform]
        - ninja                                  # [aarch64 and (python_impl == 'pypy')]
      host:
        - python
        - setuptools >=59.0.0
        - cython
        # Allow numpy pinnings to be managed by conda-forge global dependencies
        # See also <https://matrix.to/#/!SOyumkgPRWoXfQYIFH:matrix.org/$17156774815028VNLdj:matrix.org?via=matrix.org&via=gitter.im&via=salt-rock-lamp.ems.host>
        - numpy
        - numpy <2.0a0
        - versioneer ==0.28
        - pip
        - tomli
        - ninja                                  # [aarch64 and (python_impl == 'pypy')]
      run:
        - python
        - setuptools >=59.0.0
        - scipy >=0.14,<1.14
        - filelock
        - etuples
        - logical-unification
        - minikanren
        - cons
        - {{ pin_compatible("numpy") }}

    test:
      imports:
        - pytensor
      commands:
        - pytensor-cache help
        - pip check
        - python -c "import pytensor; print(pytensor.config.blas__ldflags); print(pytensor.config)"
        - python check-for-warnings.py allowed-warnings-base.txt
      requires:
        - pip
      files:
        - check-for-warnings.py
        - allowed-warnings-base.txt

  - name: pytensor
    build:
      # NOTE: Keep this line synchronized with the identical one above.
      skip: true  # [py<310]
      script:
        - echo "Nothing to build here, just add dependencies."
    requirements:
      host:
        - python
      run:
        - python
        - {{ pin_subpackage('pytensor-base', exact=True) }}
        - {{ compiler('c') }}  # [not win]
        - {{ stdlib("c") }}    # [not win]
        - {{ compiler('cxx') }}  # [not win]
        - gxx  # [linux]
        - {{ compiler('m2w64_c') }}  # [win]
        - {{ stdlib("m2w64_c") }}    # [win]
        - {{ compiler('m2w64_cxx') }}  # [win]

        - m2w64-toolchain  # [win]
        # The libpython conda-forge package seems to be a wrapper package
        # which configures m2w64-toolchain for Python.
        # <https://github.com/conda-forge/libpython-feedstock/blob/main/recipe/bld.bat>
        - libpython >=2.2  # [win]

        # mkl-service is only available for linux-64, win-64, and osx-64.
        # Use accelerate for osx-arm64.
        # For everything else, use openblas.
        - mkl-service  # [linux64 or win64 or (osx and not arm64)]
        - accelerate  # [osx and arm64]
        - openblas  # [not (linux64 or win64 or osx)]
        # For some reason we also need the "blas" package. Otherwise we get reports
        # of "cblas.h: No such file or directory" at import time.
        # Ref: <https://github.com/conda-forge/aesara-feedstock/issues/80>
        - blas
    test:
      imports:
        - pytensor
        - pytensor.configdefaults
      commands:
        - pytensor-cache help
        - pip check
        - python -c "import pytensor; print(pytensor.config.blas__ldflags); print(pytensor.config)"
        - python -c "import pytensor; assert pytensor.config.blas__ldflags != '', 'Blas flags are empty'"
        - python check-for-warnings.py allowed-warnings-main.txt
      requires:
        - pip
      files:
        - check-for-warnings.py
        - allowed-warnings-main.txt

about:
  home: https://github.com/pymc-devs/pytensor
  license: BSD-3-Clause
  summary: An optimizing compiler for evaluating mathematical expressions.
  license_file: LICENSE.txt
  dev_url: https://github.com/pymc-devs/pytensor/
  doc_url: https://pytensor.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - aseyboldt
    - maresb
    - michaelosthege
    - twiecki
